export const SIMULATION_CAP = 20;
export const TICK_INTERVAL_MS = 5000;
export const TICK_SPAWN_PROBABILITY = 0.15;
export const SIMULATED_AUTO_RESOLVE_MINUTES = 3;
export const CUSTOMER_FOLLOWUP_PROBABILITY = 0.2;
export const MIN_FOLLOWUP_GAP_SECONDS = 8;
export const MAX_SIMULATED_MESSAGES = 14;
